### ISSUE TITLE
Lists concept might be wrong place ? 

### ISSUE THREAD

**Issue by fu7mu4** [exercism/common-lisp#523]
Now Lists concept is under Arithmetic concept in the syllabus.
But I think Lists concept should be under Cons concept.

**Comment by verdammelt** [comment]
Thanks for bringing this up.

It shows up that way in the UI because the concept exericse `leslies-lists` has a pre-requisite of `arithmetic` (as well as `cons` and `symbol`). But the question is - why have hat pre-requisite?

I'll review the exercise to see what it uses of the arithmetic concept and perhaps we can remove that pre-requisite.

**Comment by verdammelt** [comment]
In review - looks like that concept is not needed - i'll remove it.
